# Generated by Django 4.1.5 on 2023-01-25 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_watchescategory_watches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watches',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='API.watchescategory'),
        ),
    ]
